name: gunjae_app
description: Gunjae Modern Camping App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  intl: ^0.18.1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  cached_network_image: ^3.3.0
  flutter_material_symbols: ^0.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
